// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Plc.Ads")>]
[<assembly: AssemblyProductAttribute("FSharp.Plc.Ads")>]
[<assembly: AssemblyDescriptionAttribute("Project has no summmary; update build.fsx")>]
[<assembly: AssemblyVersionAttribute("0.0.3")>]
[<assembly: AssemblyFileVersionAttribute("0.0.3")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Plc.Ads"
    let [<Literal>] AssemblyProduct = "FSharp.Plc.Ads"
    let [<Literal>] AssemblyDescription = "Project has no summmary; update build.fsx"
    let [<Literal>] AssemblyVersion = "0.0.3"
    let [<Literal>] AssemblyFileVersion = "0.0.3"
    let [<Literal>] AssemblyConfiguration = "Release"
